name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest ruff  # Install Ruff here

      # Run Ruff format check
      - name: Run Ruff format check
        run: ruff format --check

      - name: Debug pytest test collection
        run: pytest --collect-only

      # Run tests
      # - name: Run tests
      #   run: pytest --rootdir= ./Homework1



