name: Run Tests

on:
  push:
    branches:
      - main  # Runs CI on push to the main branch
  pull_request:
    branches:
      - main  # Runs CI on pull requests to main
  workflow_dispatch:  # 👈 This allows manual triggering


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install pytest
      - name: Run tests
        run: pytest Homework1/


